### ISSUE TITLE
Target invocation Exception

### ISSUE THREAD

**Issue by Kaizen86** [Somfic/EliteAPI#62]
```[14:18:01.799 TRACE] [EliteAPI.Event.Provider.EventProvider]
 Could not convert json to EventBase
  Target invocation  - Exception has been thrown by the target of an invocation.

 [{Json: { "timestamp":"2020-08-29T13:07:58Z", "event":"ShipTargeted", "TargetLocked":true, "Ship":"
 anaconda", "ScanStage":1, "PilotName":"$cmdr_decorate:#name=Tinvanno [RoA];", "PilotName_Localised"
 :"CMDR Tinvanno [RoA]", "PilotRank":"Elite", "SquadronID":"ROAR" }}]

  Json reader  - Could not convert string to integer: ROAR. Path 'SquadronID', line 1, position 254.
 1: at EliteAPI.Event.Provider.EventProvider.ProcessJsonEvent(String json)
 2: at EliteAPI.Event.Provider.EventProvider.InvokeFromJsonMethod(MethodBase method, String json)
 3: at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder,
 Object[] parameters, CultureInfo culture)
 4: at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters,
 Object[] arguments)
 5: at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig,
 Boolean constructor)```

**Comment by Kaizen86** [comment]
EliteAPI/Event/Models/ShipTargetedEvent.cs, line 57

```cs
[JsonProperty("SquadronID")]
public int SquadronId { get; internal set; }
```
Should be

```cs
[JsonProperty("SquadronID")]
public string SquadronId { get; internal set; }
```

**Comment by Somfic** [comment]
Thank you!
